micronaut:
  application:
    name: cdsi
  executors:
    enclave-jni:
      type: fixed
      # Note: this must never exceed `NumTCS` in `cds.conf`
      number-of-threads: 1
  metrics:
    enabled: true
    export:
      statsd:
        enabled: false
  server:
    netty:
      # don't compress
      compression-threshold: 1073741824  # 1G
      compression-level: 0
    port: 8082

logger:
  levels:
    # The Cosmos client is pretty chatty
    com.azure.cosmos: WARN

authentication:
  sharedSecret: dYOGTIEBMhHz0Oq81qUOMktyFqHTo+cEPf6RKnksk50=

enclave:
  enclaveId: 0f6fd79cdfdaa5b2e6337f534d3baf999318b0c462a7ac1f41297a3e4b424a57
  availableEpcMemory: 3200000
  loadFactor: 1.6
  shards: 10
  # token-secret: dYOGTIEBMhHz0Oq81qUOMktyFqHTo+cEPf6RKnksk50=
  # simulated: true
  # return-acis-without-uaks: true

logger:
  levels:
    org.signal: TRACE

endpoints:
  all:
    port: 8082
    sensitive: false

accountTable:
  region: eu-west-2
  tableName: live_accounts
  streamName: cdsi-account-updates-stream

leakyBucketLimit:
  connections:
    bucket-size: 10
    leak-rate-scalar: 10
    leak-rate-duration: PT1M

tokenRateLimit:
  # 6 permits/hr -> 52560 permits per year
  bucket-size: 50000
  leak-rate-scalar: 6
  leak-rate-duration: PT1H

redis:
  uris: redis://localhost:6379